### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by franmastran** [LuteOrg/lute-v3#404]
When I try to make a book this pops up
Hmm, something went wrong ...

Platform: Windows-10-10.0.19045-SP0

Version: 3.3.1

In docker?: False

Stack trace:

Traceback (most recent call last):
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\book\routes.py", line 111, in new
    book = repo.add(b)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\book\model.py", line 59, in add
    dbbook = self._build_db_book(book)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\book\model.py", line 85, in _build_db_book
    b = DBBook.create_book(book.title, lang, book.text, book.max_page_tokens)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\models\book.py", line 178, in create_book
    tokens = language.parser.get_parsed_tokens(segment, language)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\parse\space_delimited_parser.py", line 37, in get_parsed_tokens
    return self._parse_to_tokens(clean_text, language)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\parse\space_delimited_parser.py", line 70, in _parse_to_tokens
    self.parse_para(para, lang, tokens)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\parse\space_delimited_parser.py", line 91, in parse_para
    m = self.preg_match_capture(pattern, text)
  File "C:\Users\Francisco\Desktop\LUTE\envlute\lib\site-packages\lute\parse\space_delimited_parser.py", line 46, in preg_match_capture
    matches = re.finditer(pattern, subject, flags=re.IGNORECASE)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\re.py", line 247, in finditer
    return _compile(pattern, flags).finditer(string)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 836, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 554, in _parse
    code1 = _class_escape(source, this)
  File "C:\Users\Francisco\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 349, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 37

- Browser chrome
- How you've installed Lute python

**Comment by jzohrab** [comment]
Hi @franmastran — I assume you’re trying to make a Japanese book. See if the notes in https://github.com/LuteOrg/lute-v3/issues/403 help you out: make sure mecab is installed, and that you’re using the Japanese parser in your language.  Let me know how it goes. 👋

**Comment by jzohrab** [comment]
Closing, no response.
